---
title: "Project template"
author: "Anonymous"
output: 
  pdf_document: 
    toc: yes
    toc_depth: 1
---

# 1. Introduction

(motivate the problem and )


https://www.kaggle.com/harlfoxem/housesalesprediction



# 2. Dataset description

```{r}
library(rstan)
library(ggplot2)
library(dplyr)
library(GGally)
library(corrplot)
library(reshape2)

```



```{r}
houseprice = read.csv("data/kc_house_data.csv", header = TRUE)
head(houseprice)
```

```{r}
houseprice = houseprice[,3:21]
  
```

```{r}
#pearson correlation matrix
M <- cor(houseprice)
corrplot(M, method = "circle")
```

```{r}
#ggpairs(houseprice  %>% select(price, bathrooms, sqft_living))
ggpairs(houseprice, columns = c("price", "bathrooms"), ggplot2::aes(colour=zipcode)) 

```



# 3. Model description


## 3.1 Prior choices

(these are good priors because referece to something)

## 3.2 Running the model

(amount of chains etc and the final fit)


# 4. Convergences diagnostics


# 5. Posterior predictive checking



# 6. Model comparison


# 7. Predictive performance assesment


# 8. Sensitivity analysis



# 9. Discussion













